[package]
name = "library_stdnums"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "regex_vs_string_methods"
harness = false

[lib]
bench = false
